# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
events_list = [
  [ "Kids Summer Workshop", "Smaaash: Gurgaon","This program will give the students first-hand experience of how news is collated, processed & disseminated through various media vehicles like TV, Newspaper and Online. This program is meant for students with varied interests, as journalism covers topics ranging from Sports, Entertainment, Social behavior, Tourism, Political, Legal, Electronic, Defense, Wildlife, and Economy etc.Hence, this course would be a perfect grooming opportunity for students helping them discover where their passion lies."],
  [ "7th Jagran Film Festival","Sirifort Auditorium: Delhi,", "The 7th edition of Jagran Film Festival is back in town with a fun-filled week long film bonanza at the Siri Fort Auditoria, New Delhi. The Annual filmy fiesta begins on July 1, 2016 for five days and screens over 100 films across a variety of sections. The largest touring film festival in the world begins its 100 day run from New Delhi and travels to 14 cities before culminating in Mumbai end September.The festival brings together the Best of Indian and International Cinema across genres." ],
  [ "Asia Pacific Boxing Championship", "Thyagaraj Sports Complex: Delhi","IOS Boxing Promotions present to you the first ever pro boxing championship of the knockout King Vijender Singh, in India. After having won 6 knockout fights ever since the boxer turned professional, this will be the first time that he will fight in front of his home crowd, on 16th July 2016. Not only will the audience get a chance to see their favourite sensation in action, but also get entertained by the run up of six other fights that follow up to the main Asia-Pacific pro boxing championship title. The night will also see performances and appearances of celebrities from the entertainment world. " ],
  [ "Skilled India Investors Meet 2016", "Amity University, Sector 125 : Noida","Skilled India Investors Meet 2016 (SIIM2016) is holding Business Summit and Business Awards to explore growth oriented business opportunities from worldwide. It will be a platform for to 'Meet the Specialist Advisor'. An opportunity to meet, discuss and resolve business issues with International Industry Experts, Govt Agencies, Domestic Market Leaders from world-leading organisations, all under one roof. Each Specialist Advisor represents a different step or business growth journey, providing bespoke advice to help take your business to the next level." ],
  [ "Seminar About Establishing Business in CANADA", "The Westin Hotel: Gurgaon", "'G-Seminars' is organizing a seminar about establishing business in Canada, from August to September 2016 in 10 cities all over India. This seminar will be a place to gather all the entrepreneurs and business entities/organizations all over India. It is expected to get a great response from companies of all scales.This seminar will have guests from all industries, guests who like to establish their entity/business in Canada by having thorough knowledge about business opportunities in Canada" ],
  [ "Astelier's Weekend Theatre Programme", "Atelier Studio: New Delhi ", "Atelier's Weekend Theatre Programme (WTP) got started after receiving enormous number of requests and suggestions from the friends of Atelier who have a full time career in a non-theatre zone and want to follow their passion alongside, devoting time in a constructive vocation. Atelier took a call and designed the paradigm unimaginable, yet realistic. It's the perfect mix of theory and practice, which suits the needs of working professionals, students, teachers and actors in the age bracket of 16-50." ],
  [ "Six Sigma Green Belt Training and Certification Program", "KPMG, Mahalaxmi: Mumbai", "A 4-day comprehensive 32-hour contact program designed with adaptive learning methodology. The program is delivered by experienced professionals from Big 4 Consultancy Firm, who will share thoughts to nurture experiential learning on the go." ],
  [ "A Rendezvous With Ramzan - Iftar Food Walk!", "Chawri Bazar Metro Station: Delhi", "Ironically, the month of Ramzan, where one fasts for 30 days, gives rise to some of the most delicious and mouth watering treats in the city. And all of this is available only during the special period of Ramzan when the Iftar is taken after sunset. Delhi 6 is the hub of this hullabaloo and that's where the host will be taking you on this Old Delhi Ramzan walk." ],
  [ "Abhimanyu - The Fastest Feet", "Kingdom Of Dreams: Gurgaon", "It is a story showcasing the journey of an Indian classical dancer. His journey to take his culture and art to every part of world fulfills many other commitments like his father's dream, village's problems, etc. While first half shows different colours, cultures, relations and festivals of India, second half shows the major transition of this native boy when he is recognized and taken to USA by an international Broadway dancer" ],
  [ "Delhi's Night Food Tour Bus!", "Hauz Khas Metro Station: Delhi", "On this SeekSherpa Food Tour Bus travel across Delhi for mouthwatering bites legends are made of! Gorge on delicacies youve only read and heard about. Book your seat on the SeekSherpa Delhi Food Tour Bus as we take you on a journey full of food and laughter to taste some of Delhis tastiest foods in less than 3 hours!
    Meet just outside the Hauz Khas Metro station on the Yellow Line at the Mayfair Garden Gate where your Sherpa will meet you there and help you board the Food Tour Bus" ],
  [ "Dilli Haat Through a Cultural Lens", "INA Metro Gate No. 3: Delhi", "The aim of this cultural tour of Dilli Haat hosted via SeekSherpa is to capture the essence of the distinguished traditions of India from her 29 states all in under 3 hours. At Dilli Haat each state displays its own art form, food, and culture. Dilli Haat is the culmination of all these states presenting their own wares beautifully.Through the walk you will see and interact with various artisans and their traditional work. You will get an insight into their different cultures, where they come from, and the history of their art forms and traditions. " ],
  [ "Four Play - An Evening of Comedy", "Epicentre at Apparel House: Gurgaon", "Bring your partner along for a night of Four-play, a stand-up comedy show where four comedians tickle you in the right place - your funny bone. These comedians have been hand-picked on the basis of their jokes, their looks, but mostly their combined ability of totalling to the number four. With uniquely ridiculous styles of comedy, they will joke about meaningless stuff which will, ironically, add a lot of value to your lives. Bump into them at Epicentre for some laughs. " ],
  [ "Vir Das' Unbelievable!","Kamani Auditorium: Delhi", "In the summer of 2006, Vir Das flew an Air India plane while high on prescription painkillers. Later that very year, he signed his first film and had a romantic encounter with a top Bollywood actress. Two years later, he shared a fistbump with the President." ],
  [ "Antar Yatra", "The Music Academy: Chennai", "'Antar-Yatra' is a dance narrative featuring Sharmila Biswas, Srijan Chatterjee, Lakshmi Parthasarathy Athreya, Amrita Lahiri and Sashwati Garai Ghosh. The narrative is presented in three popular dance forms of the Coast of the Coromander: Bharatanatyam, Kuchipudi and Odishi. Songs have been researched on, translated to and sung in six different Indian languages. Noted for the originality in composition, technique and stage design, Sharmila Biswas' choreography for this production involves the intensity of traditional movement skills combined with contemporary concepts." ]
]

Event.transaction do
  events_list.each do |name, venue, description|
    start_time = rand(24..168).hours.from_now
    end_time = start_time + rand(3..10).hours
    ticket_price = [100, 200, 400, 500,750, 1000, 1500].sample

    Event.create!( name: name, venue: venue, description: description, start_time: start_time, end_time: end_time, ticket_price: ticket_price  )
  end
end
